### ISSUE TITLE
New-AGMHost method has issues with alternateipaddresses

### ISSUE THREAD

**Issue by kirantejaj** [Actifio/AGMPowerCLI#26]
I was getting an error - 404 while adding a new host. Even though the host addition is successful, the error is not desirable. I made the change to New-AGMHost method locally on my machine and it worked. Please check once.

 if ($alternateip)
    {
        $alternateipaddresses = @( $($alternateip.Split(",")) )
    }else {
        $alternateipaddresses = @()
    }

**Comment by aussiestorblog** [comment]
Good suggestion.   have made this change in version 0.0.0.50

**Comment by kirantejaj** [comment]
Thank you.
